# Generated by Django 4.2 on 2023-04-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcpl_app', '0002_recipe_delete_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
